### PR TITLE
[cypress-v10] Fix snapshot file location different in open vs run

### PR DESCRIPTION
**Pull request by wilsonpage**

### CODE REVIEW

**Comment by simonsmith** [comment]
Thanks @wilsonpage!

**Comment by simonsmith** [comment]
Published in `5.0.3`

**Comment by wilsonpage** [comment]
Worth noting this could be regarded as a 'breaking change' as the final
snapshot image paths will be different. Although it was inconsistent
between run/open to start with 🙃

**Comment by simonsmith** [comment]
Yeah, was on the fence about whether it was fixing the existing issue. So went with patch for now

**Comment by wilsonpage** [comment]
Do you think this will ever get merged back into the original project?

**Comment by simonsmith** [comment]
I don't think so. I even contacted the maintainer on Twitter and he didn't reply so I guess it will stay in limbo

**Comment by mateuszwrobel** [comment]
[simonsmith](https://github.com/simonsmith) I just downloaded your version and this code is not present there. Version (5.0.3) is correct, but those changes are not.

**Comment by simonsmith** [comment]
@mateuszwrobel You're quite right. Strange, it seems like the `prepublish` didn't work. I've built manually and published `5.0.4` now

I can see the change here - https://www.runpkg.com/?@simonsmith/cypress-image-snapshot@5.0.4/command.js

**Pull request merged**
