### PR TITLE
fix: if Cypress env `failOnSnapshotDiff` is `true`, `isFailOnSnapshotDiff` is `true`

### PR DESCRIPTION
**Pull request by MaximilianoAdaro**
Issue reported [here](https://github.com/simonsmith/cypress-image-snapshot/issues/22)

### CODE REVIEW

**Comment by simonsmith** [comment]
This just needs the pipeline fixed, looks like ESLint and also the commit message needs to follow [conventional commits](https://github.com/pvdlg/conventional-changelog-metahub#commit-types)

Thanks!

**Comment by MaximilianoAdaro** [comment]
Updated! Just needed to change commit message @simonsmith

**Comment by simonsmith** [comment]
I'm still seeing an ESLint error though, relating to Prettier. Otherwise looks good

**Comment by MaximilianoAdaro** [comment]
> I'm still seeing an ESLint error though, relating to Prettier. Otherwise looks good

There we go, it should be solved now

**Comment by simonsmith** [comment]
Thanks for this! Will get it released with some other fixes shortly

**Pull request merged**
