### PR TITLE
feat: Add retry functionality

### PR DESCRIPTION
**Pull request by alhan-garcia**

### CODE REVIEW

**Comment by alhan-garcia** [comment]
@simonsmith this PR aims to add the retry functionality in the command. 
I use this package for my tests and there are several scenarios where the images don't load immediatly and the command fails immediatly since it throws an error on snapshot diffs (no way to assert the image has loaded through other cypress assertions)

**Comment by simonsmith** [comment]
Is this different to the retry functionality built into Cypress? That's what has been working for me

**Comment by alhan-garcia** [comment]
Yes, it's different. This retries the matchImageSnapshot command recursively until it times out or it succeeds, as far as I'm aware the cypress retry functionality retries the "it" block which is not what I'm looking for, in fact there's someone who tried to implement this back in 2020: https://github.com/jaredpalmer/cypress-image-snapshot/pull/128/files

There's still some rough edges I need to iron out but I wanted to present the idea even if not fully finished.  

My use case is retrying the command in canvas elements where the content takes a second or two to load, however since matchImageSnapshot throws an error and stops test execution as soon as a diff is encountered then it's not possible to do it currently, in summary my problems with this command are:

* When test fails in matchImageSnapshot() the test execution is stopped
* If the test execution is not stopped (by setting Cypress.env("failOnSnapDiff", false)) and matchImageSnapshot() passes then it returns null which doesn't provide information to either fail the test or retry the command

**Comment by simonsmith** [comment]
I see, I've encountered issues like this in the past but instead I would use something like `cy.get('element').should('be.visible')` or any kind of assertion to prove things are on the page before proceeding with the snapshot (perhaps checking for text, or that a file has loaded).

I'm just aware of accidentally adding complexity when Cypress itself has alternatives. I'm using this plugin on multiple projects with a lot of tests and this tends to be the approach I've used to create consistent snapshots

**Comment by alhan-garcia** [comment]
Thanks for the advice, unfortunately I have exhausted my options with this canvas element, there's no change in html or css that would allow me to perform an assertion before the image is fully rendered before taking a screenshot, it just pops after a while. If you have any experience with this kind of elements it'd be greatly appreciated. I can maintain my fork if you think this adds too much unnecessary complexity

**Comment by simonsmith** [comment]
I noticed there is a delay of `5000` in the config, so wouldn't this be the similar to:

```ts
// something that renders canvas first
cy.wait(5000)
cy.matchImageSnapshot()
```

It's not the ideal way to write tests but at least the delay is not hidden.
It feels like this might be something worth solving outside the plugin for such a specific use case as yours

**Comment by alhan-garcia** [comment]
Fair enough, I'm closing this pr

**Pull request closed without merging**
