### PR TITLE
refactor: remove unnecessary console.log

### PR DESCRIPTION
**Pull request by zuzusik**

### CODE REVIEW

**Comment by simonsmith** [comment]
Thanks for catching this. Could you update your commit message to be compliant with [conventional-changelog](https://github.com/pvdlg/conventional-changelog-metahub#commit-types). Probably a `refactor` makes sense here.

If you rebase on master it should run the CI on pull requests as well, as I've made a quick update

**Comment by zuzusik** [comment]
@simonsmith done!

**Comment by zuzusik** [comment]
But seems like CI needs some sort of approval to run:

https://github.com/simonsmith/cypress-image-snapshot/actions/runs/5212557046

Screenshot 2023-06-08 at 10 45 51 AM

**Comment by simonsmith** [comment]
Yep, think you need approval for first contributions. It's running now. Will merge when complete

**Comment by simonsmith** [comment]
Thanks for the contribution!

**Pull request merged**
